Softvision-Argentina/hr-app

- 1.Domain/Domain.Model/Process.cs
- 1.Domain/Domain.Model/TechnicalStage.cs
- 1.Domain/Domain.Services.Impl/Profiles/TechnicalStageProfile.cs
- 1.Domain/Domain.Services/Contracts/Stage/TechnicalStage/CreateTechnicalStageContract.cs
- 1.Domain/Domain.Services/Contracts/Stage/TechnicalStage/ReadedTechnicalStageContract.cs
- 1.Domain/Domain.Services/Contracts/Stage/TechnicalStage/UpdateTechnicalStageContract.cs
- 4.Clients/ApiServer.Contracts/Stage/TechnicalStage/CreateTechnicalStageViewModel.cs
- 4.Clients/ApiServer.Contracts/Stage/TechnicalStage/ReadedTechnicalStageViewModel.cs
- 4.Clients/ApiServer.Contracts/Stage/TechnicalStage/UpdateTechnicalStageViewModel.cs
- 4.Clients/WebApi/ClientApp/src/app/processes/processes/processes.component.ts
- 4.Clients/WebApi/ClientApp/src/app/stages/technical-stage/technical-stage.component.html
- 4.Clients/WebApi/ClientApp/src/app/stages/technical-stage/technical-stage.component.ts
- 4.Clients/WebApi/ClientApp/src/entities/technical-stage.ts
Added a second seniority field in the technical stage.
> Technical stage two seniorities

- 4.Clients/WebApi/ClientApp/src/app/stages/hr-stage/hr-stage.component.html
- 4.Clients/WebApi/ClientApp/src/app/stages/technical-stage/technical-stage.component.html
Feedback input needed dinamic size's . I'ts done.
> inputs doned.

- 1.Domain/Domain.Services.Impl/Profiles/CandidateProfile.cs
- 1.Domain/Domain.Services.Impl/Services/CandidateService.cs
- 1.Domain/Domain.Services/Contracts/Candidate/CreateCandidateContract.cs
- 1.Domain/Domain.Services/Contracts/Candidate/ReadedCandidateContract.cs
- 1.Domain/Domain.Services/Contracts/Candidate/UpdateCandidateContract.cs
- 2.Infrastructure/Domain.Services.Repositories.EF/SeedMigrator.cs
- 4.Clients/ApiServer.Contracts/Candidates/CreateCandidateViewModel.cs
- 4.Clients/ApiServer.Contracts/Candidates/ReadedCandidateViewModel.cs
- 4.Clients/ApiServer.Contracts/Candidates/UpdateCandidateViewModel.cs
- 4.Clients/WebApi/ClientApp/src/app/candidates/add/candidate-add.component.ts
- 4.Clients/WebApi/ClientApp/src/app/candidates/candidates.component.ts
- 4.Clients/WebApi/ClientApp/src/app/candidates/details/candidate-details.component.ts
- 4.Clients/WebApi/ClientApp/src/app/processes/process-contact/process-contact.component.ts
- 4.Clients/WebApi/ClientApp/src/app/processes/processes/processes.component.html
- 4.Clients/WebApi/ClientApp/src/app/processes/processes/processes.component.ts
- 4.Clients/WebApi/ClientApp/src/entities/Candidate-Profile.ts
- 4.Clients/WebApi/ClientApp/src/entities/candidate.ts
The process component now brings all the candidateProfile object for each candidate instead of just an "int Id". Prevents the error "Cannot read property of undefined" from happening.
> Process data management Update/Fix 

- 0.Core/Core/ApplicationErrorMainCodes.cs
- 1.Domain/Domain.Model/Exceptions/Postulant/PostulantErrorSubCodes.cs
- 1.Domain/Domain.Model/Exceptions/Postulant/PostulantException.cs
- 1.Domain/Domain.Services.Impl/Services/PostulantService.cs
- 1.Domain/Domain.Services/Interfaces/Services/IPostulantService.cs
- 4.Clients/ApiServer/Controllers/PostulantsController.cs
- 4.Clients/WebApi/ClientApp/src/app/postulants/postulants.component.html
- 4.Clients/WebApi/ClientApp/src/app/postulants/postulants.component.ts
Agrego comportamiento para los botones de info y eliminar
> botones de eliminar e informacion de postulantes

- 4.Clients/WebApi/ClientApp/src/app/stages/client-stage/client-stage.component.ts
- 4.Clients/WebApi/ClientApp/src/app/stages/hr-stage/hr-stage.component.ts
- 4.Clients/WebApi/ClientApp/src/app/stages/offer-stage/offer-stage.component.ts
- 4.Clients/WebApi/ClientApp/src/app/stages/technical-stage/technical-stage.component.ts
Item de trello : En declined poner razon
> Stages: 'declined' now shows the reason textbox, like rejected

- 4.Clients/WebApi/ClientApp/src/app/processes/processes/processes.component.ts
Al editar el proceso el modal abre en el 'currentStage'
> Editar Process

- 4.Clients/WebApi/ClientApp/src/app/processes/processes/processes.component.html
- 4.Clients/WebApi/ClientApp/src/app/processes/processes/processes.component.ts
- If the process its finished then open edit in 'OfferStage'
- Clicking outside of the modals calls 'closeModal'
> Validaciones en los procesos

- 1.Domain/Domain.Services.Tests/ValidatorTester/Candidate/CreateCandidateContractValidatorTester.cs
Located on 
>Domain/Domain.Services.Impl/Validators/Candidate/CreateCandidateContractValidator.cs
> Added unit testing for fluent validations

- 1.Domain/Domain.Services.Tests/Domain.Services.Tests.csproj
- 1.Domain/Domain.Services.Tests/Impl/Services/TaskServiceTest.cs
Add unit test's Domain.Services.Impl.Services.TaskService
> Unit test domain services impl services task

- 1.Domain/Domain.Services.Tests/ValidatorTester/CandidateProfile/CreateCandidateProfileContractValidatorTester.cs
- 1.Domain/Domain.Services.Tests/ValidatorTester/CandidateProfile/UpdateCandidateProfileContractValidatorTester.cs
Locate on:
>hr-app\1.Domain\Domain.Services.Impl\Validators\CandidateProfile
- CreateCandidateProfileContractValidator.cs
- UpdateCandidateProfileContractValidator.cs
> Added unit testing for fluent validations / CandidateProfile

- 1.Domain/Domain.Services.Tests/ValidatorTester/Community/CreateCommunityContractValidatorTester.cs
- 1.Domain/Domain.Services.Tests/ValidatorTester/Community/UpdateCommunityContractValidatorTester.cs
Located on 
>hr-app\1.Domain\Domain.Services.Impl\Validators\Community
>  Added unit testing for fluent validations / Community

- 1.Domain/Domain.Services.Impl/Services/ProcessService.cs
Now they are order by the start date of the process.
> Fix candidates order bug

- 4.Clients/ApiServer.Tests/ApiServer.Tests.csproj
- 4.Clients/ApiServer.Tests/Controllers/TasksControllerTest.cs
Add unit test's ApiServer.Controllers.TasksController
> Unit test api server controllers tasks controller

- 4.Clients/ApiServer.Tests/Controllers/UserControllerTest.cs
Add unit test's ApiServer.Controllers.UserController
> Unit test api server controllers user controller

- 1.Domain/Domain.Services.Impl/Services/UserService.cs
- 1.Domain/Domain.Services.Tests/Impl/Services/UserServiceTest.cs
- Add UserServiceTest
- Remove UserService's DataBaseContext dependency and clean code
> Unit test domain services impl services user 

- 2.Infrastructure/Domain.Services.Repositories.EF/SeedMigrator.cs
- 4.Clients/WebApi/ClientApp/src/app/dashboard/dashboard.component.html
- 4.Clients/WebApi/ClientApp/src/app/nav-menu/nav-menu.component.html
Now you can choose if you want to show or hide the new "Weekly Candidates dashboard" in the manage preferences modal.
> Fixed nav modal bug and added "Weekly Candidates dashboard" to the seed migrator

- 1.Domain/Domain.Services.Tests/Impl/Services/SkillServiceTest.cs
> Feature unit test domain services impl services skillservice

- 4.Clients/ApiServer/appsettings.Development.json
- 4.Clients/ApiServer/appsettings.json
- 4.Clients/WebApi/ClientApp/src/app/login/csoft-signin.component.html
- 4.Clients/WebApi/ClientApp/src/app/login/csoft-signin.component.ts
- 4.Clients/WebApi/ClientApp/src/app/services/auth.service.ts
[https://trello.com/c/CGZHtdiS/118-regular-login-unauthorized-user-error-message-is-not-being-shown](url)
> adding a try-catch to avoid the undefined

- 4.Clients/ApiServer.Tests/Controllers/SkillsControllerTest.cs
> Feature unit test apiserver controllers skillscontroller

- 4.Clients/ApiServer.Tests/Controllers/SkillTypesControllerTest.cs
- 4.Clients/ApiServer.UnitTests/Controllers/SkillTypesControllerTest.cs
- 4.Clients/ApiServer.UnitTests/Controllers/SkillsControllerTest.cs
> Feature unit test apiserver controllers skilltypescontroller

- 0.Core/Core/HttpUtility.cs
- 1.Domain/Domain.IntegrationTests/Core/ServiceFixture.cs
- 2.Infrastructure/Persistance.EF/Extensions/ContextExtension.cs
- 4.Clients/ApiServer.FunctionalTests/Core/ApiFixture.cs
- 4.Clients/ApiServer.FunctionalTests/Core/BaseApiTest.cs
Added reset of all identity ids at disposing context, and modify api test helper methods to better handle requests of every type
> Testing core methods enhancement

- 2.Infrastructure/Domain.Services.Repositories.EF/SeedMigrator.cs
- 4.Clients/WebApi/ClientApp/src/app/services/base.service.ts
Se agrego el usuario para Gabriel Damalis en el Context respectivamente.
Se cambio a minuscula el require que se hace a un paquete de rxjs en el base service.
> Agregado nuevo usuario y ajuste de case en un require

- 4.Clients/WebApi/ClientApp/src/app/app-config/app.config.ts
- 4.Clients/WebApi/ClientApp/src/app/services/auth.service.ts
- 4.Clients/WebApi/ClientApp/src/app/services/base.service.ts
- 4.Clients/WebApi/ClientApp/src/app/services/candidate.service.ts
- 4.Clients/WebApi/ClientApp/src/app/services/config.service.ts
- 4.Clients/WebApi/ClientApp/src/app/services/days-off.service.ts
- 4.Clients/WebApi/ClientApp/src/app/services/employee.service.ts
- 4.Clients/WebApi/ClientApp/src/app/services/notificationsService.ts
- 4.Clients/WebApi/ClientApp/src/app/services/postulants.service.ts
- 4.Clients/WebApi/ClientApp/src/app/services/process.service.ts
- 4.Clients/WebApi/ClientApp/src/app/services/task.service.ts
- 4.Clients/WebApi/ClientApp/src/app/services/user.service.ts
Card in Trello: 
<blockquote class="trello-card"><a href="https://trello.com/c/F1ZKFGxz/131-actualizar-syntax-de-import-de-todos-los-observables">Actualizar syntax de Import de todos los Observables</a></blockquote>
> Updated syntax for Observables import on services

- 4.Clients/ApiServer/Controllers/NotificationController.cs
- 4.Clients/ApiServer/Startup.cs
Modified the method for getting the username from the httpcontext
> Notifications - UserName

- 2.Infrastructure/Domain.Services.Repositories.EF.UnitTests/BaseRepositoryTest.cs
- 2.Infrastructure/Domain.Services.Repositories.EF.UnitTests/SkillTypeRepositoryTest.cs
- 2.Infrastructure/Domain.Services.Repositories.EF.UnitTests/StageItemRepositoryTest.cs
- 2.Infrastructure/Domain.Services.Repositories.EF.UnitTests/TaskItemRepositoryTest.cs
- 2.Infrastructure/Domain.Services.Repositories.EF.UnitTests/TaskRepositoryTest.cs
- 2.Infrastructure/Domain.Services.Repositories.EF.UnitTests/TechnicalStageRepositoryTest.cs
- 2.Infrastructure/Domain.Services.Repositories.EF.UnitTests/UserRepositoryTest.cs
Move MockUnitOfWork to BaseRepositoryTest
Add SkillTypeRepositoryTest, StageItemRepositoryTest, TaskItemRepositoryTest, TaskRepositoryTest and TechnicalStageRepositoryTest
> Feature unit test modify baserepositorytest

- 1.Domain/Domain.IntegrationTests/Services/CandidateProfileServicesIntegrationTest.cs
- 1.Domain/Domain.Services.Impl/Validators/Candidate/CreateCandidateContractValidator.cs
- 1.Domain/Domain.UnitTests/Validators/Candidate/CreateCandidateContractValidatorTester.cs
All test pass with this changes
> Fixed broken test

- .github/pull_request_template.md
This is a template to help ease the workflow of making new PR's and mark the in a simple way, the relevant details of the request.
> New template for PR created

- 1.Domain/Domain.Services.Impl/Validators/Community/CreateCommunityContractValidator.cs
- 1.Domain/Domain.UnitTests/Validators/Community/CreateCommunityContractValidatorTester.cs
- 4.Clients/ApiServer.Contracts/Community/UpdateCommunityViewModel.cs
- 4.Clients/ApiServer.FunctionalTests/Controller/CommunityControllerFunctionalTest.cs
Added functional test for community controller.
Catch a bug that in api/community [Post] method, backend was not validating any property of the passed DTO.
**[Hold until @DevgaboxSoftvision checks if this change does not break any valuable resource in the Front-end]**
> Added Community functional test & bugfix

- 1.Domain/Domain.Services.Impl/Validators/Candidate/CreateCandidateContractValidator.cs
- 4.Clients/WebApi/ClientApp/src/app/candidates/add/candidate-add.component.html
- 4.Clients/WebApi/ClientApp/src/app/candidates/add/candidate-add.component.ts
- 4.Clients/WebApi/ClientApp/src/app/candidates/candidates.component.ts
- 4.Clients/WebApi/ClientApp/src/app/processes/processes/processes.component.ts
- 4.Clients/WebApi/ClientApp/src/entities/candidate.ts
> DNI Validator

- 4.Clients/ApiServer/Controllers/UserController.cs
- 4.Clients/WebApi/ClientApp/src/app/candidates/candidates.component.html
- 4.Clients/WebApi/ClientApp/src/app/candidates/candidates.component.ts
- 4.Clients/WebApi/ClientApp/src/app/nav-menu/nav-menu.component.html
- 4.Clients/WebApi/ClientApp/src/app/nav-menu/nav-menu.component.ts
- 4.Clients/WebApi/ClientApp/src/app/processes/processes/processes.component.html
- 4.Clients/WebApi/ClientApp/src/app/processes/processes/processes.component.ts
- 4.Clients/WebApi/ClientApp/src/entities/enums/searchbar-placeholder-enum.ts
INSERT_BRIEF_DESCRIPTION
**This PR is blocked by the following PR:** #
**NetCoreApi HOT FIX Deploy
*To mark an option, replace white space with an "x" inside the brackets. This way: [x]*
- [ X ] Bug fix (non-breaking change which fixes an issue)
*To mark an option, replace white space with an "x" inside the brackets. This way: [x]*
**INSERT_IMPORTANT_NOTE_HERE**
> fixed bug in processes.component.html and UserController.cs
